### PR TITLE
New Gource Video!

### PR DESCRIPTION
**Pull request by alcarney**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Nice! :+1:

Travis is failing?

**Comment by alcarney** [comment]
@drvinceknight Yeah, there's a link in one of the reference articles that for some bizarre reason will periodically fail the build 🤔

**Comment by drvinceknight** [comment]
Cool, I'm happy for this to be merged (not sure what the protocol is anymore).

**Comment by alcarney** [comment]
@drvinceknight I believe @StephanieAngharad will be doing it when she gets a minute

**Pull request merged**
