### PR TITLE
Adding a landing page!

### PR DESCRIPTION
**Pull request by alcarney**
All the cool websites these have a "landing page" so I thought I'd add
one to the website. A landing page is essentially an overview as to why
you should use a product/site/thing or in our case come to code club.

This essentially covers everything that was on the old home page but
hopefully it's presented a bit better. Also the redundant list of blog
posts has been removed since that's now in the archive.

Note: I've written in the stylesheets for this in such a way that a simple import should be enough to update your theme to work with the new page.

Hope you like it!

(Screenshots made using the classic theme)
2016-02-14-165220_1280x800_scrot
2016-02-14-165241_1280x800_scrot
2016-02-14-165250_1280x800_scrot
2016-02-14-165300_1280x800_scrot

### CODE REVIEW

**Comment by alcarney** [comment]
Okay in the race to open this against my battery dying I forgot to run the tests....

Will fix when I get power back

**Comment by Huaraz2** [comment]
Does it break the tests?

**Comment by alcarney** [comment]
> Will fix when I get power back 

Yes I think so

**Comment by alcarney** [comment]
@alcarney Testing telegram bot

**Comment by timothyf1** [comment]
@alcarney Trying again @Huaraz2 It's missing the alt text on images and a couple of interntal links are broken

**Comment by alcarney** [comment]
@timothyf1 Trying again since my comment didn't show up last time

**Comment by Huaraz2** [comment]
@alcarney @timothyf1 ok cool thanks for letting me know

**Comment by drvinceknight** [comment]
@Huaraz2 What is going on?

**Comment by Huaraz2** [comment]
Seeing as it has now passed the tests, I will pull it in. :smiling_imp:

**Pull request merged**
