### PR TITLE
Rewriting the reference and getting involved pages

### PR DESCRIPTION
**Pull request by alcarney**
- Projects can now be toggled as 'active' or 'not active'
- To mark a project as active simply add `active: true` to the project's
  data in `_data/projects.yml`
- Active projects are listed on the getinvolved page with a link to the
  full list of projects
- Divided languages between "real" languages and "forfun" languages and
  have seperate sections for them on the main reference page
- To mark a language as "forfun" simply add the tag `forfun` in the YAML
  front matter of the language's page
- Programming challenges have been moved from the reference page to the
  getinvolved page
- Updated home page content to reflect the new structure of the site

### CODE REVIEW

**Comment by alcarney** [comment]
Just as well we added travis!

**Comment by Huaraz2** [comment]
What did you break? :imp:

**Comment by alcarney** [comment]
Links to languages - fixed now

**Comment by Huaraz2** [comment]
Ok, looked at the commit but could not see any difference that was all. Will merge now :computer: :script:

**Pull request merged**
