### PR TITLE
Adding Travis to the Website

### PR DESCRIPTION
**Pull request by alcarney**
Using the Continuous Integration page on the jekyll website as a guide
this should now enable travis build testing for the website. The
following things should be tested:

- Whether `jekyll build` succesfully builds the website
- Using a gem called `htmlproofer` the following checks should be
  performed on the site
  + All (local and external) images exist and are loaded correctly
  + All (internal and external) links are not dead (as raised in #9)
  + All HTML markup is well formed
  + All script elements load correctly

Sorry for the mess of commits but it took some persuation to get things moving

### CODE REVIEW

**Comment by drvinceknight** [comment]
Ok, so travis isn't quite setup right, as it should be appearing 'happy' with a tick here, like this: https://www.dropbox.com/s/y3mqgdlqyy7yusp/Screenshot%202015-11-23%2018.22.11.png?dl=0

**Comment by alcarney** [comment]
Don't we have to enable it for the repository first on the Travis website?

**Comment by alcarney** [comment]
Or to put it another way - what am I missing?

**Comment by drvinceknight** [comment]
Can you post the link to the travis build? Switching to gitter in case you're there.

**Comment by Huaraz2** [comment]
its all good so I will merge :smiling_imp:

**Pull request merged**
