### PR TITLE
Removed extra space

### PR DESCRIPTION
**Pull request by timothyf1**
This pull requests removes a little annoying space and make the code a bit simpler 

This change is using something that was introduced into jekyll 3.

screenshot from 2016-02-02 12-53-49

### CODE REVIEW

**Comment by Huaraz2** [comment]
it keeps crashing for some reason so not going to pull this in. :smiling_imp:

**Comment by Huaraz2** [comment]
Also it does not work, the ...Pending... tag is gone. see pic below:
image

**Comment by timothyf1** [comment]
You aren't running it with jekyll 3.0.0 locally 
I think its because in the gem file (I not using bundle due to errors) has the gem gh-pages which hasn't been updated means you still using the old version of jekyll when building the website

**Comment by timothyf1** [comment]
It's working here http://timothyf1.github.io/CardiffMathematicsCodeClub.github.io/getinvolved.html

**Pull request merged**
