### PR TITLE
Deleting the "main" div

### PR DESCRIPTION
**Pull request by alcarney**
*Note* The changes here depend on #168 

Ok not as bad as it sounds, but there is a div in our HTML that serves
no purpose so this removes it. Again this shouldn't affect how the site looks just trying to clean up the internals

### CODE REVIEW

**Comment by Huaraz2** [comment]
@alcarney Run the tests and I will pull it in, the fact that travis is not always testing this is starting to get annoying

**Comment by drvinceknight** [comment]
@Huaraz2 What do you mean Travis is not always running tests?

**Comment by Huaraz2** [comment]
@drvinceknight If you look back at some of the PR's made in the last month you will notice that the last commit is pointless, this is because we are making the commit in order for travis to run the tests on the PR.

**Comment by Huaraz2** [comment]
as it passed I will pull it in.

**Pull request merged**
