### PR TITLE
Add twitter cards for blog posts

### PR DESCRIPTION
**Pull request by alcarney**
- This is an experiment having just come accross
  [twitter cards.](https://dev.twitter.com/cards/types/summary)
- By adding a few `<meta>` tags in our html, whenever people tweet a
  link to the website, twitter scrapes the linked page looking for these
  tags and if they are found displays a nice looking card in the body of
  a tweet.
- This PR is an attempt to add the necessary meta tags to implement
  this for blog posts.

- I have also created a twitter account for code club (no idea if people
  want this so currently it's not really visible - I want to hear your
  thoughts on this.)
- If people decide they want a twitter account for code club then these
  cards can be linked to the account and we in theory can get some
  metrics on how people interact with tweets containing links to the
  site (again no idea if people want this - let me know your thoughts).

- To test this, it's basically a case of adding these tags and then
  tweeting a link and checking to see if twitter can parse this and add
  the card appropriately.

### CODE REVIEW

**Comment by Huaraz2** [comment]
What is the twitter handle @alcarney ?

**Comment by alcarney** [comment]
@Huaraz2 @cardiffmathcode

**Comment by Huaraz2** [comment]
> -  To test this, it's basically a case of adding these tags and then tweeting a link and checking to see if twitter can parse this and add the card appropriately.

IS there any way to write a test to do this, wouldn't it need to be connected to a live account?

**Comment by alcarney** [comment]
@Huaraz2 There is a validator offered by twitter but the meta tags need to be on the live site for it to work

**Comment by Huaraz2** [comment]
@alcarney Ok cool cool

**Comment by alcarney** [comment]
@Huaraz2 The link to a live account is only needed if we want to collect engagement data

**Pull request merged**
