### PR TITLE
Fix themes close #143

### LINKED ISSUE #143: Unable to read words on landing page with new themes
The landing page with `Geriant's theme`:
image

The landing page with `Classic Inverted` theme:
image

Landing page with `Matrix` theme:
image

As you can see in the above pics, the writing on the landing page is either very difficult or impossible to read. Any ideas as to how we fix this @alcarney? Could we possibly make the `$background-color` variable come up behind the words (in all the themes apart from `Geriant's Theme` it would then be readable).

### PR DESCRIPTION
**Pull request by Huaraz2**
This fixes #143. I have made the changes to the themes as per @alcarney's advice. As you can see in the pics below, only when you use **Geriant's Theme** is the writing still unreadable.

***Geriant's Theme*** landing page:
image

***Classic Inverted*** theme landing page:
image

As for the Matrix theme, I have made my own landing.scss file and made some changes to the index.html file so that the landing page looks like this when you have ***The Matrix*** theme on:

image

image

image

image

### CODE REVIEW

**Comment by alcarney** [comment]
Nice :+1:

Just a couple of things...

- It's probably best if you put your `_matrixlandingpage` theme file in a `_matrix` folder as it will help keep themes separate and they will all be moved into `_themes` folder in a forthcoming pr.

- Not sure what happened to the html on the index page but it looks like (if I'm reading the diff correctly) that some of the opening <p> tags have been replaced by extra <br> tags. So it would be good of they could be put back (not sure why the tests didn't pick it up)

**Comment by alcarney** [comment]
Forget the second point I've realised what you did :)

**Comment by Huaraz2** [comment]
@alcarney Ok will move the `matrixlandingpage` later. :smiling_imp:

**Comment by Huaraz2** [comment]
@alcarney All done. :smiling_imp:

**Comment by alcarney** [comment]
Nice :+1:

**Pull request merged**
