### PR TITLE
Tweaks to Cardiff Rouge

### PR DESCRIPTION
**Pull request by alcarney**
- Cleaned up the blog styles and hopefully made things look sharper
- Made code snippets more useful by choosing a monospace font so
  hopefully they are more clear and helpful especially for languages
  like Python
- Reorganised the internals of the theme hopefully making things more sane.
- Minor version bump

### CODE REVIEW

**Comment by Huaraz2** [comment]
@alcarney can't pull this in as it has conflicts with the main branch.

**Comment by alcarney** [comment]
@Huaraz2 OK, will fix later

**Comment by alcarney** [comment]
@Huaraz2 Fixed

**Comment by Huaraz2** [comment]
cool cool :smiling_imp:

**Pull request merged**
