### PR TITLE
Gist depreciation close #139

### LINKED ISSUE #139: Depreciate Gists?
Do we want to remove support for gists on the site? Or at least push for code to be put into the backtick syntax like here on github.

- It would help make the site look more consistent and people have more control over how their themes look
- It might reduce compexity? By keeping code and content all in one place?

### PR DESCRIPTION
**Pull request by Huaraz2**
I have removed the gists from all of the language pages and blog posts (even yours @timothyf1), I have also made the `Just in time for the new Term: PyDiff!` blog post to the pydiff catergary. (all pics are made using The Matrix theme, some are made at 67% veiw instead of 100% as this gave me more of an overview).

image

image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by alcarney** [comment]
@Huaraz2 Didn't we delete the pydiff category sometime before Christmas? :p

**Comment by Huaraz2** [comment]
@alcarney Nope

**Comment by Huaraz2** [comment]
@alcarney You just changed the category from website to news

**Comment by Huaraz2** [comment]
@alcarney It's now in both the news and pydiff category

**Pull request merged**
