### PR TITLE
Inverted Colours theme

### PR DESCRIPTION
**Pull request by Huaraz2**
I have made my first theme for the website, more are on the way...

image

image

### CODE REVIEW

**Comment by alcarney** [comment]
Screenshots? :)

**Comment by Huaraz2** [comment]
seriously?

**Comment by alcarney** [comment]
Why not? 

Also it's probably best you change all the '_layouts/x.scss`  imports into a single `_layout.scss` that way you won't have to update the theme when we makes changes to the layout.

**Comment by Huaraz2** [comment]
what?

**Comment by Huaraz2** [comment]
I am in my windows partion at the moment, the screen shots will take time

**Comment by alcarney** [comment]
No worries.

I got the formatting wrong on my last comment hopefully it's fixed now. 

I'm talking about the `@import` lines in your `css/inverted.scss` file

**Comment by Huaraz2** [comment]
ok what do you want me to do? I copied what was in @geraintpalmer's theme

**Comment by alcarney** [comment]
Yeah that one needs changing also

Have a look at how main and minimal do it, that's how all themes which want to use the default layout should import it from now on

**Comment by Huaraz2** [comment]
ok will have to change that in a bit

**Comment by Huaraz2** [comment]
I will change all of the themes in a bit.

**Comment by Huaraz2** [comment]
@alcarney it's all done, plus enjoy the screenshots. :smiling_imp:

**Comment by alcarney** [comment]
Nice!

**Pull request merged**
